version: "3.9"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.19
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./conf/logstash/:/usr/share/logstash/pipeline/
      - ./conf/ruby/:/usr/lib/firefly/ruby/
      - ./conf/logstash_data/:/etc/stardust/pipeline/
      - ./conf/certificates:/etc/stardust/pipeline/certificates/
    stdin_open: true
    tty: true
    environment:
      - XPACK_MONITORING_ENABLED=false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
